#!/usr/bin/env python3
import argparse
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser("Publish medical and natural combined tables into one summary markdown")
    p.add_argument("--medical", required=True)
    p.add_argument("--natural", required=True)
    p.add_argument("--dest", required=True)
    return p.parse_args()


def strip_title(content):
    lines = content.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join(lines[1:]).lstrip()
    return content.strip()


def main():
    args = parse_args()
    medical = Path(args.medical).read_text(encoding="utf-8")
    natural = Path(args.natural).read_text(encoding="utf-8")
    lines = [
        "# Experiment Master Tables With my_merge Ablations",
        "",
        "- Medical domain and natural-domain-control results are generated by scripts from `eval_summary.csv` files.",
        "- Highlight rule remains unchanged: highest value is bold, second-highest distinct value is underlined.",
        "",
        "## Medical Domain",
        "",
        strip_title(medical),
        "",
        "## Natural Domain Control",
        "",
        strip_title(natural),
        "",
    ]
    dest = Path(args.dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
